#!/bin/bash

. ~/admin-shell/ADDRESS
. ~/admin-shell/interrupt_all.sh

rm Hypersomnia-for-Linux.sfx
wget $DOWNLOADS_HOST/builds/latest/Hypersomnia-for-Linux.sfx
chmod +x ./Hypersomnia-for-Linux.sfx
rm -rf hypersomnia
./Hypersomnia-for-Linux.sfx
mkdir hypersomnia/user
cp admin-shell/user/* hypersomnia/user/
cd hypersomnia

. ~/admin-shell/run_dedicated.sh
. ~/admin-shell/run_masterserver.sh
