#!/bin/bash
BUILDS=/var/www/html/builds
VERSION=$1
SET_TO_LATEST_FLAG=$2
TARGET_PATH="$BUILDS/$VERSION"

sudo rm -rf $TARGET_PATH
sudo mv ~/uploads/$VERSION $TARGET_PATH
#sudo chown -R www-data:www-data $TARGET_PATH

if [[ "$SET_TO_LATEST_FLAG" == "--set-to-latest" ]]; then
	~/remote-shell/set_latest_version $VERSION

	export WEBHOOK_URL=$(cat ~/.update_notification_webhook_url)

	curl -F 'payload_json={ "username": "Downloads page", "embeds": [{ "author": {"name": "'"$VERSION"'"}, "thumbnail": { "url": "https://cdn.discordapp.com/attachments/284466566874267649/1061035478800928780/image.png" }, "color":  52224, "title": "Update available!", "description": "Hypersomnia will install updates on the next launch."} ] }' $WEBHOOK_URL
fi
