#!/bin/bash
BUILDS=/var/www/html/builds
VERSION=$1
SET_TO_LATEST_FLAG=$2
TARGET_PATH="$BUILDS/$VERSION"

sudo rm -rf $TARGET_PATH
sudo mv ~/uploads/$VERSION $TARGET_PATH
#sudo chown -R www-data:www-data $TARGET_PATH

if [[ "$SET_TO_LATEST_FLAG" == "--set-to-latest" ]]; then
	echo "--set-to-latest flag is set. Latest version will be set to $VERSION."
	~/remote-shell/set_latest_version $VERSION

	echo "Sending update notification."
	~/remote-shell/update_notification $VERSION
fi
