#!/bin/bash
BUILDS=/var/www/html/builds
VERSION=$1
SET_TO_LATEST_FLAG=$2
TARGET_PATH="$BUILDS/$VERSION"

sudo rm -rf $TARGET_PATH
sudo mv ~/uploads/$VERSION $TARGET_PATH
sudo chown -R www-data:www-data $TARGET_PATH

if [[ "$SET_TO_LATEST_FLAG" == "--set-to-latest" ]]; then
	~/remote-shell/set_latest_version $VERSION
fi
