#!/bin/bash

. ~/remote-shell/ADDRESS

rm -f Hypersomnia-Headless.AppImage
wget $DOWNLOADS_HOST/builds/latest/Hypersomnia-Headless.AppImage
chmod +x ./Hypersomnia-Headless.AppImage

. ~/remote-shell/restart_servers
