#!/bin/bash

. ~/remote-shell/ADDRESS
. ~/remote-shell/interrupt_all.sh

rm Hypersomnia-for-Linux.sfx
wget $DOWNLOADS_HOST/builds/latest/Hypersomnia-for-Linux.sfx
chmod +x ./Hypersomnia-for-Linux.sfx
rm -rf hypersomnia
./Hypersomnia-for-Linux.sfx
mkdir hypersomnia/user
cp remote-shell/user/* hypersomnia/user/
cd hypersomnia

. ~/remote-shell/run_dedicated.sh
. ~/remote-shell/run_masterserver.sh
