#!/bin/bash

VERSION=$1
export WEBHOOK_URL=$(cat ~/.update_notification_webhook_url)

curl -F 'payload_json={ "username": "Downloads page", "embeds": [{ "author": {"name": "'"$VERSION"'"}, "thumbnail": { "url": "https://cdn.discordapp.com/attachments/284466566874267649/1061035478800928780/image.png" }, "color":  52224, "title": "Update available!", "description": "Hypersomnia will install updates on the next launch."} ] }' $WEBHOOK_URL
